export enum Category {
  Packs = "packs",
  Cocktails = "cocktails",
  Mocktails = "mocktails",
  Gins = "gins",
  Whiskeys = "whiskeys",
  Vodkas = "vodkas",
  Food = "food",
  Wine = "wine",
  Beers = "beers",
  Sangrias = "sangrias",
  Shots = "shots",
}

export interface MenuItem {
  id: string;
  name: { en: string; pt: string };
  description: { en: string; pt: string };
  price: number;
  category: Category;
  sales: number;
  image?: string;
}

export const menuItems: MenuItem[] = [
  // PACKS PARA PARTILHAR
  {
    id: "pack-gin-mar",
    name: { en: "6 Passionfruit Gins", pt: "6 Gins Maracujá" },
    description: { en: "Gin, passionfruit, lime juice, sugar.", pt: "Gin, maracujá, sumo de lima, açúcar." },
    price: 35.00,
    category: Category.Packs,
    sales: 120,
  },
  {
    id: "pack-gin-mor",
    name: { en: "6 Strawberry Gins", pt: "6 Gins Morango" },
    description: { en: "Gin, strawberry, lime juice, sugar.", pt: "Gin, morango, sumo de lima, açúcar." },
    price: 35.00,
    category: Category.Packs,
    sales: 95,
  },
  {
    id: "pack-reg-sag",
    name: { en: "Sagres Tray (5 Finos)", pt: "Régua 5 Finos Sagres" },
    description: { en: "20cl per unit.", pt: "20cl" },
    price: 6.50,
    category: Category.Packs,
    sales: 1540,
  },
  {
    id: "pack-reg-hei",
    name: { en: "Heineken Tray (5 Finos)", pt: "Régua 5 Finos Heineken" },
    description: { en: "25cl per unit.", pt: "25cl" },
    price: 7.50,
    category: Category.Packs,
    sales: 1420,
  },
  {
    id: "pack-can-sag",
    name: { en: "6 Sagres Mugs", pt: "6 Canecas Sagres" },
    description: { en: "40cl per unit.", pt: "40cl" },
    price: 12.50,
    category: Category.Packs,
    sales: 840,
  },
  {
    id: "pack-can-hei",
    name: { en: "6 Heineken Mugs", pt: "6 Canecas Heineken" },
    description: { en: "50cl per unit.", pt: "50cl" },
    price: 15.00,
    category: Category.Packs,
    sales: 760,
  },
  {
    id: "pack-sho-cas",
    name: { en: "6 House Shots", pt: "6 Shots da casa" },
    description: { en: "Vodka, passionfruit or strawberry puree.", pt: "Vodka, puré de maracujá ou morango." },
    price: 10.00,
    category: Category.Packs,
    sales: 520,
  },

  // COCKTAILS
  {
    id: "cock-whi",
    name: { en: "White Linen", pt: "White Linen" },
    description: { en: "Hendrick's, St. Germain, cucumber, soda.", pt: "Hendrick's, st. germain, pepino, soda." },
    price: 11.00,
    category: Category.Cocktails,
    sales: 45,
  },
  {
    id: "cock-haz",
    name: { en: "Hazelnut Espresso", pt: "Hazelnut Espresso" },
    description: { en: "Baileys, hazelnut liqueur, coffee, vodka, cinnamon, sugar.", pt: "Baileys, licor de avelã, café, vodka, canela e açúcar." },
    price: 10.00,
    category: Category.Cocktails,
    sales: 62,
  },
  {
    id: "cock-esp",
    name: { en: "Espresso Martini", pt: "Espresso Martini" },
    description: { en: "Absolut, coffee liqueur, coffee.", pt: "Absolut, licor de café, café." },
    price: 7.00,
    category: Category.Cocktails,
    sales: 180,
  },
  {
    id: "cock-mos",
    name: { en: "Moscow Mule", pt: "Moscow Mule" },
    description: { en: "Absolut, lime juice, ginger beer, ginger foam.", pt: "Absolut, sumo de lima, ginger beer, espuma de gengibre." },
    price: 8.00,
    category: Category.Cocktails,
    sales: 145,
  },
  {
    id: "cock-gin",
    name: { en: "Passionfruit Gin", pt: "Gin Maracujá" },
    description: { en: "Gin, passionfruit, lime juice, sugar.", pt: "Gin, maracujá, sumo de lima, açúcar." },
    price: 7.00,
    category: Category.Cocktails,
    sales: 210,
  },
  {
    id: "cock-mac",
    name: { en: "Maça Dourada", pt: "Maça Dourada" },
    description: { en: "Jack Daniel's Apple, Sommersby.", pt: "Jack daniel's apple, sommersby." },
    price: 7.00,
    category: Category.Cocktails,
    sales: 85,
  },
  {
    id: "cock-moj",
    name: { en: "Mojito", pt: "Mojito" },
    description: { en: "Rum, mint, lime juice, sugar, soda.", pt: "Rum, hortelã, sumo de lima, açúcar, soda." },
    price: 7.00,
    category: Category.Cocktails,
    sales: 320,
  },
  {
    id: "cock-moj-mar",
    name: { en: "Passionfruit Mojito", pt: "Mojito Maracujá" },
    description: { en: "Rum, mint, lime juice, passionfruit, sugar, soda.", pt: "Rum, hortelã, sumo de lima, maracujá, açúcar, soda." },
    price: 7.00,
    category: Category.Cocktails,
    sales: 190,
  },
  {
    id: "cock-por",
    name: { en: "Porn Star Martini", pt: "Porn Star Martini" },
    description: { en: "Vanilla vodka, passoa, passionfruit, lime juice, sugar.", pt: "Vodka de baunilha, passoa, maracujá, sumo de lima, açúcar." },
    price: 7.00,
    category: Category.Cocktails,
    sales: 240,
  },
  {
    id: "cock-neg",
    name: { en: "Negroni", pt: "Negroni" },
    description: { en: "Tanqueray, campari, vermouth.", pt: "Tanqueray, campari, vermouth." },
    price: 7.00,
    category: Category.Cocktails,
    sales: 75,
  },
  {
    id: "cock-teq",
    name: { en: "Tequila Sunrise", pt: "Tequila Sunrise" },
    description: { en: "Tequila, orange juice, grenadine.", pt: "Tequila, sumo de laranja, groselha." },
    price: 6.50,
    category: Category.Cocktails,
    sales: 110,
  },
  {
    id: "cock-whi-sou",
    name: { en: "Whiskey Sour", pt: "Whiskey Sour" },
    description: { en: "Jameson Black Barrel, lime juice, sugar, egg white.", pt: "Jameson black barrel, sumo de lima, açúcar, clara de ovo." },
    price: 8.00,
    category: Category.Cocktails,
    sales: 95,
  },
  {
    id: "cock-pin",
    name: { en: "Pinacolada", pt: "Pinacolada" },
    description: { en: "Havana 3, coconut, pineapple.", pt: "Havana 3, coco, ananás." },
    price: 8.00,
    category: Category.Cocktails,
    sales: 130,
  },
  {
    id: "cock-bas",
    name: { en: "Basil Smash", pt: "Basil Smash" },
    description: { en: "Gin, basil, lime juice, sugar, egg white.", pt: "Gin, manjericão, sumo de lima, açúcar, clara de ovo." },
    price: 7.00,
    category: Category.Cocktails,
    sales: 55,
  },

  // MOCKTAILS
  {
    id: "mock-por",
    name: { en: "Sunset", pt: "Por do Sol" },
    description: { en: "Orange juice, grenadine.", pt: "Sumo de laranja, groselha." },
    price: 3.00,
    category: Category.Mocktails,
    sales: 85,
  },
  {
    id: "mock-pan",
    name: { en: "Pink Panther", pt: "Pantera Cor de Rosa" },
    description: { en: "Strawberry, peach, orange, whipped cream.", pt: "Morango, pêssego, laranja, chantilly." },
    price: 3.00,
    category: Category.Mocktails,
    sales: 120,
  },
  {
    id: "mock-vir",
    name: { en: "Virgin Colada", pt: "Virgem Colada" },
    description: { en: "Coconut puree, pineapple.", pt: "Puré de coco, ananás." },
    price: 3.00,
    category: Category.Mocktails,
    sales: 75,
  },
  {
    id: "mock-rea",
    name: { en: "Realito", pt: "Realito" },
    description: { en: "Passionfruit, orange, pineapple, grenadine.", pt: "Maracujá, laranja, ananás, groselha." },
    price: 3.00,
    category: Category.Mocktails,
    sales: 65,
  },
  {
    id: "mock-pas",
    name: { en: "Passion Fizz", pt: "Passion Fizz" },
    description: { en: "Passionfruit, passionfruit puree, soda.", pt: "Maracujá, puré de maracujá, soda." },
    price: 4.00,
    category: Category.Mocktails,
    sales: 45,
  },

  // GINS
  {
    id: "gin-ada-ori",
    name: { en: "Adamus Original", pt: "Adamus Original" },
    description: { en: "Lemon, 1724 tonic.", pt: "Limão, tónica 1724." },
    price: 10.00,
    category: Category.Gins,
    sales: 88,
  },
  {
    id: "gin-ada23",
    name: { en: "Adamus Signature 2023", pt: "Adamus Signature 2023" },
    description: { en: "Lemon, 1724 tonic.", pt: "Limão, tónica 1724." },
    price: 13.00,
    category: Category.Gins,
    sales: 34,
  },
  {
    id: "gin-ada21",
    name: { en: "Adamus Signature 2021", pt: "Adamus Signature 2021" },
    description: { en: "Lemon, 1724 tonic (LAST UNITS).", pt: "Limão, tónica 1724 ÚLTIMAS UNIDADES." },
    price: 18.00,
    category: Category.Gins,
    sales: 12,
  },
  {
    id: "gin-eng",
    name: { en: "Engine", pt: "Engine" },
    description: { en: "Lime, 1724 tonic.", pt: "Lima, tónica 1724." },
    price: 10.00,
    category: Category.Gins,
    sales: 42,
  },
  {
    id: "gin-nor",
    name: { en: "Nordés", pt: "Nordés" },
    description: { en: "Grape, bay leaf, Fever Tree Mediterranean tonic.", pt: "Uva, louro, tónica Fever Tree Mediterranean." },
    price: 9.00,
    category: Category.Gins,
    sales: 156,
  },
  {
    id: "gin-hen",
    name: { en: "Hendricks", pt: "Hendricks" },
    description: { en: "Cucumber, Fever Tree Indian tonic.", pt: "Pepino, tónica Fever Tree Indian." },
    price: 11.00,
    category: Category.Gins,
    sales: 132,
  },
  {
    id: "gin-mon",
    name: { en: "Monkey 47", pt: "Monkey 47" },
    description: { en: "Lemon, 1724 tonic.", pt: "Limão, tónica 1724." },
    price: 13.00,
    category: Category.Gins,
    sales: 67,
  },
  {
    id: "gin-mar",
    name: { en: "Gin Mare", pt: "Gin Mare" },
    description: { en: "Basil, 1724 tonic.", pt: "Manjericão, tónica 1724." },
    price: 10.00,
    category: Category.Gins,
    sales: 58,
  },
  {
    id: "gin-tri",
    name: { en: "Le Tribute", pt: "Le Tribute" },
    description: { en: "Lime, orange, 1724 tonic.", pt: "Lima, laranja, tónica 1724." },
    price: 10.00,
    category: Category.Gins,
    sales: 39,
  },
  {
    id: "gin-bla",
    name: { en: "Black Pig", pt: "Black Pig" },
    description: { en: "Lemon, juniper, Fever Tree Mediterranean tonic.", pt: "Limão, zimbro, tónica Fever Tree Mediterranean." },
    price: 10.00,
    category: Category.Gins,
    sales: 44,
  },
  {
    id: "gin-sha",
    name: { en: "Sharish", pt: "Sharish" },
    description: { en: "Apple, Fever Tree Mediterranean tonic.", pt: "Maça, tónica Fever Tree Mediterranean." },
    price: 10.00,
    category: Category.Gins,
    sales: 78,
  },
  {
    id: "gin-bee",
    name: { en: "Beefeater", pt: "Beefeater" },
    description: { en: "Orange, lemon, Schweppes tonic.", pt: "Laranja, limão, tónica schweeps." },
    price: 6.50,
    category: Category.Gins,
    sales: 198,
  },
  {
    id: "gin-tan",
    name: { en: "Tanqueray", pt: "Tanqueray" },
    description: { en: "Lime, orange, Schweppes tonic.", pt: "Lima, laranja, tónica schweeps." },
    price: 6.50,
    category: Category.Gins,
    sales: 215,
  },
  {
    id: "gin-sev",
    name: { en: "Tanqueray Sevilla", pt: "Tanqueray Sevilla" },
    description: { en: "Orange, Fever Tree Mediterranean tonic.", pt: "Laranja, tónica Fever Tree Mediterranean." },
    price: 8.00,
    category: Category.Gins,
    sales: 112,
  },
  {
    id: "gin-tan-ten",
    name: { en: "Tanqueray Ten", pt: "Tanqueray Ten" },
    description: { en: "Premium Tanqueray Gin.", pt: "Gin Tanqueray Premium." },
    price: 10.00,
    category: Category.Gins,
    sales: 56,
  },
  {
    id: "gin-mar-mil",
    name: { en: "Martin Millers", pt: "Martin Millers" },
    description: { en: "Classic Gin.", pt: "Gin Clássico." },
    price: 8.00,
    category: Category.Gins,
    sales: 73,
  },

  // WHISKEYS
  {
    id: "whi-mac",
    name: { en: "The Macallan 12 Double Cask", pt: "The Macallan 12 Double Cask" },
    description: { en: "Premium Scotch Whiskey (Bottle 150€).", pt: "Whiskey Scotch Premium (Garrafa 150€)." },
    price: 15.00,
    category: Category.Whiskeys,
    sales: 25,
  },
  {
    id: "whi-jac",
    name: { en: "Jack Daniel’s", pt: "Jack Daniel’s" },
    description: { en: "Tennessee Whiskey (Bottle 70€).", pt: "Whiskey Tennessee (Garrafa 70€)." },
    price: 7.00,
    category: Category.Whiskeys,
    sales: 340,
  },
  {
    id: "whi-jac-a",
    name: { en: "Jack Daniel’s Flavors", pt: "Jack Daniel’s Apple/Fire/Cinnamon" },
    description: { en: "Apple, Fire or Cinnamon (Bottle 70€).", pt: "Apple, Fire ou Cinnamon (Garrafa 70€)." },
    price: 7.00,
    category: Category.Whiskeys,
    sales: 180,
  },
  {
    id: "whi-jac-s",
    name: { en: "Jack Daniel’s Single Barrel", pt: "Jack Daniel’s Single Barrel" },
    description: { en: "Bottle 120€.", pt: "Garrafa 120€." },
    price: 12.00,
    category: Category.Whiskeys,
    sales: 45,
  },
  {
    id: "whi-car",
    name: { en: "Cardhu", pt: "Carduh" },
    description: { en: "Single Malt (Bottle 110€).", pt: "Single Malt (Garrafa 110€)." },
    price: 11.00,
    category: Category.Whiskeys,
    sales: 62,
  },
  {
    id: "whi-jam",
    name: { en: "Jameson", pt: "Jameson" },
    description: { en: "Irish Whiskey (Bottle 60€).", pt: "Whiskey Irlandês (Garrafa 60€)." },
    price: 6.50,
    category: Category.Whiskeys,
    sales: 410,
  },
  {
    id: "whi-jam-b",
    name: { en: "Jameson Black Barrel", pt: "Jameson Black Barrel" },
    description: { en: "Bottle 70€.", pt: "Garrafa 70€." },
    price: 8.00,
    category: Category.Whiskeys,
    sales: 125,
  },
  {
    id: "whi-joh-r",
    name: { en: "Johnnie Walker Red Label", pt: "Johnnie Walker Red Label" },
    description: { en: "Bottle 60€.", pt: "Garrafa 60€." },
    price: 6.50,
    category: Category.Whiskeys,
    sales: 290,
  },
  {
    id: "whi-joh-b",
    name: { en: "Johnnie Walker Black Label", pt: "Johnnie Walker Black Label" },
    description: { en: "Bottle 75€.", pt: "Garrafa 75€." },
    price: 8.00,
    category: Category.Whiskeys,
    sales: 115,
  },
  {
    id: "whi-dew-8",
    name: { en: "Dewar’s 8 Years", pt: "Dewar’s 8 Anos" },
    description: { en: "Bottle 65€.", pt: "Garrafa 65€." },
    price: 7.00,
    category: Category.Whiskeys,
    sales: 85,
  },
  {
    id: "whi-dew-15",
    name: { en: "Dewar’s 15 Years", pt: "Dewar’s 15 Anos" },
    description: { en: "Bottle 90€.", pt: "Garrafa 90€." },
    price: 10.00,
    category: Category.Whiskeys,
    sales: 54,
  },

  // VODKAS
  {
    id: "vod-mix",
    name: { en: "Mix Red Bull / Premium Tonic", pt: "MIX RED BULL / TÓNICA PREMIUM" },
    description: { en: "Mixer for your vodka.", pt: "Mixer para a sua vodka." },
    price: 1.00,
    category: Category.Vodkas,
    sales: 650,
  },
  {
    id: "vod-gre",
    name: { en: "Grey Goose", pt: "Grey Goose" },
    description: { en: "Premium French Vodka (Bottle 90€).", pt: "Vodka Francesa Premium (Garrafa 90€)." },
    price: 10.00,
    category: Category.Vodkas,
    sales: 145,
  },
  {
    id: "vod-cir",
    name: { en: "Ciroc", pt: "Ciroc" },
    description: { en: "Bottle 80€.", pt: "Garrafa 80€." },
    price: 8.00,
    category: Category.Vodkas,
    sales: 110,
  },
  {
    id: "vod-bel",
    name: { en: "Belvedere", pt: "Belvedere" },
    description: { en: "Bottle 70cl 90€ | Bottle 3L 600€.", pt: "Garrafa 70cl 90€ | Garrafa 3L 600€." },
    price: 10.00,
    category: Category.Vodkas,
    sales: 95,
  },
  {
    id: "vod-pra",
    name: { en: "Pravda", pt: "Pravda" },
    description: { en: "Bottle 1.75L.", pt: "Garrafa 1.75L." },
    price: 200.00,
    category: Category.Vodkas,
    sales: 5,
  },
  {
    id: "vod-thr",
    name: { en: "Three Sixty", pt: "Three Sixty" },
    description: { en: "Bottle 60€.", pt: "Garrafa 60€." },
    price: 6.00,
    category: Category.Vodkas,
    sales: 230,
  },
  {
    id: "vod-abs",
    name: { en: "Absolut", pt: "Absolut" },
    description: { en: "Bottle 60€.", pt: "Garrafa 60€." },
    price: 6.00,
    category: Category.Vodkas,
    sales: 310,
  },
  {
    id: "vod-bel-42",
    name: { en: "Bellow 42", pt: "Bellow 42" },
    description: { en: "Bottle 60€.", pt: "Garrafa 60€." },
    price: 6.00,
    category: Category.Vodkas,
    sales: 180,
  },

  // FOOD
  {
    id: "foo-win",
    name: { en: "Hot Chicken Wings", pt: "Hot Chicken Wings" },
    description: { en: "8 units.", pt: "8 unidades" },
    price: 10.00,
    category: Category.Food,
    sales: 215,
  },
  {
    id: "foo-nug",
    name: { en: "Nuggets", pt: "Nuggets" },
    description: { en: "6 units or 12 units 10€.", pt: "6 unidades ou 12 unidades 10eur" },
    price: 6.00,
    category: Category.Food,
    sales: 245,
  },
  {
    id: "foo-piz",
    name: { en: "4 Mini Pizzas", pt: "4 Mini Pizzas" },
    description: { en: "Cheese, ham and oregano.", pt: "queijo, fiambre e orégãos" },
    price: 5.00,
    category: Category.Food,
    sales: 180,
  },
  {
    id: "foo-chi",
    name: { en: "Chips", pt: "Chips" },
    description: { en: "Potato sticks with salt and oregano.", pt: "batatas palito com sal e orégãos" },
    price: 4.00,
    category: Category.Food,
    sales: 560,
  },
  {
    id: "foo-gel",
    name: { en: "Ice Cream Cone", pt: "Gelado Cone" },
    description: { en: "Cream/strawberry/chocolate.", pt: "nata/morango/chocolate e nata" },
    price: 1.50,
    category: Category.Food,
    sales: 120,
  },
  {
    id: "foo-tos",
    name: { en: "Toastie", pt: "Tosta Mista" },
    description: { en: "Cheese, ham, butter and oregano.", pt: "queijo, fiambre, manteiga e orégãos" },
    price: 3.50,
    category: Category.Food,
    sales: 480,
  },

  // WINE
  {
    id: "win-maz",
    name: { en: "Mazouco Douro", pt: "Mazouco Douro" },
    description: { en: "Red/White.", pt: "tinto/branco" },
    price: 15.00,
    category: Category.Wine,
    sales: 84,
  },
  {
    id: "win-pla",
    name: { en: "Planura Alentejo", pt: "Planura Alentejo" },
    description: { en: "Red/White.", pt: "tinto/branco" },
    price: 15.00,
    category: Category.Wine,
    sales: 76,
  },
  {
    id: "win-fid",
    name: { en: "Fidalgo de Silgueiros", pt: "Fidalgo de Silgueiros" },
    description: { en: "Red.", pt: "tinto" },
    price: 15.00,
    category: Category.Wine,
    sales: 58,
  },
  {
    id: "win-ped",
    name: { en: "Pedra Cancela", pt: "Pedra Cancela" },
    description: { en: "Red/White.", pt: "tinto/branco" },
    price: 15.00,
    category: Category.Wine,
    sales: 92,
  },
  {
    id: "win-mel",
    name: { en: "Mélange À Trois", pt: "Mélange À Trois" },
    description: { en: "Red/White.", pt: "tinto/branco" },
    price: 20.00,
    category: Category.Wine,
    sales: 45,
  },
  {
    id: "win-pap",
    name: { en: "Papa Figos", pt: "Papa Figos" },
    description: { en: "Red.", pt: "tinto" },
    price: 15.00,
    category: Category.Wine,
    sales: 110,
  },
  {
    id: "win-cas",
    name: { en: "Casa de Santar", pt: "Casa de Santar" },
    description: { en: "White.", pt: "branco" },
    price: 15.00,
    category: Category.Wine,
    sales: 63,
  },
  {
    id: "win-ade-b",
    name: { en: "Adega de Penalva 'BAGA'", pt: "Adega de Penalva 'BAGA'" },
    description: { en: "Red.", pt: "tinto" },
    price: 15.00,
    category: Category.Wine,
    sales: 38,
  },
  {
    id: "win-cai",
    name: { en: "Caiado", pt: "Caiado" },
    description: { en: "Red/White.", pt: "tinto/branco" },
    price: 15.00,
    category: Category.Wine,
    sales: 54,
  },
  {
    id: "win-dia",
    name: { en: "Diálogo", pt: "Diálogo" },
    description: { en: "Red.", pt: "tinto" },
    price: 15.00,
    category: Category.Wine,
    sales: 72,
  },
  {
    id: "win-ade-m",
    name: { en: "Adega Maior Reserva 2019", pt: "Adega Maior Reserva 2019" },
    description: { en: "Red.", pt: "tinto" },
    price: 15.00,
    category: Category.Wine,
    sales: 29,
  },
  {
    id: "win-ade-a",
    name: { en: "Adega Mayor Antão Vaz 2019", pt: "Adega Mayor Antão Vaz 2019" },
    description: { en: "White.", pt: "branco" },
    price: 20.00,
    category: Category.Wine,
    sales: 21,
  },

  // CERVEJAS
  {
    id: "bee-gui",
    name: { en: "Guinness", pt: "Guinness" },
    description: { en: "44cl.", pt: "44cl" },
    price: 5.00,
    category: Category.Beers,
    sales: 210,
  },
  {
    id: "bee-fin-sag",
    name: { en: "Fino Sagres", pt: "Fino Sagres" },
    description: { en: "20cl.", pt: "20cl" },
    price: 1.50,
    category: Category.Beers,
    sales: 12400,
  },
  {
    id: "bee-fin-hei",
    name: { en: "Fino Heineken", pt: "Fino Heineken" },
    description: { en: "25cl.", pt: "25cl" },
    price: 1.70,
    category: Category.Beers,
    sales: 8900,
  },
  {
    id: "bee-can-sag",
    name: { en: "Sagres Mug", pt: "Caneca Sagres" },
    description: { en: "40cl.", pt: "40cl" },
    price: 2.50,
    category: Category.Beers,
    sales: 3100,
  },
  {
    id: "bee-can-hei",
    name: { en: "Heineken Mug", pt: "Caneca Heineken" },
    description: { en: "50cl.", pt: "50cl" },
    price: 3.00,
    category: Category.Beers,
    sales: 2800,
  },
  {
    id: "bee-hei",
    name: { en: "Heineken Bottle", pt: "Heineken" },
    description: { en: "25cl bottle.", pt: "25cl garrafa" },
    price: 1.70,
    category: Category.Beers,
    sales: 1200,
  },
  {
    id: "bee-sup",
    name: { en: "Super Bock", pt: "Super Bock" },
    description: { en: "33cl bottle.", pt: "33cl garrafa" },
    price: 2.00,
    category: Category.Beers,
    sales: 1500,
  },
  {
    id: "bee-mae",
    name: { en: "Maestra Dark Beer", pt: "Maestra Cerveja Preta" },
    description: { en: "33cl bottle.", pt: "33cl garrafa" },
    price: 2.00,
    category: Category.Beers,
    sales: 340,
  },
  {
    id: "bee-san",
    name: { en: "San Miguel Fresca", pt: "San Miguel Fresca" },
    description: { en: "33cl bottle.", pt: "33cl garrafa" },
    price: 2.50,
    category: Category.Beers,
    sales: 180,
  },
  {
    id: "bee-des",
    name: { en: "Desperados", pt: "Desperados" },
    description: { en: "33cl bottle.", pt: "33cl garrafa" },
    price: 2.50,
    category: Category.Beers,
    sales: 420,
  },

  // SANGRIAS
  {
    id: "san-tin",
    name: { en: "Red Sangria", pt: "Tinta" },
    description: { en: "Jack Fire, lime juice, sugar, red wine, orange and lemon, cinnamon, 7up.", pt: "Jack Fire, sumo de lima, açúcar, vinho tinto, gomos de laranja e limão, pau de canela, 7up" },
    price: 15.00,
    category: Category.Sangrias,
    sales: 145,
  },
  {
    id: "san-bra",
    name: { en: "White Sangria", pt: "Branca" },
    description: { en: "Jack Fire, lime juice, sugar, white wine, orange and lemon, cinnamon, 7up.", pt: "Jack Fire, sumo de lima, açúcar, vinho branco, gomos de laranja e limão, pau de canela, 7up" },
    price: 15.00,
    category: Category.Sangrias,
    sales: 130,
  },
  {
    id: "san-esp-mar",
    name: { en: "Sparkling Passionfruit Sangria", pt: "Espumante e Maracujá" },
    description: { en: "Sparkling wine, passionfruit puree, lime juice and passionfruit.", pt: "Espumante, puré de maracujá, sumo de lima e maracujá" },
    price: 20.00,
    category: Category.Sangrias,
    sales: 95,
  },
  {
    id: "san-esp-mor",
    name: { en: "Sparkling Strawberry Sangria", pt: "Espumante e Morango" },
    description: { en: "Sparkling wine, strawberry puree, lime juice and passionfruit.", pt: "Espumante, puré de morango, sumo de lima e maracujá" },
    price: 20.00,
    category: Category.Sangrias,
    sales: 85,
  },

  // SHOTS
  {
    id: "sho-cas",
    name: { en: "House Shot", pt: "Shot da Casa" },
    description: { en: "House special vodka with fruit puree.", pt: "vodka de serviço, puré de maracujá ou morango" },
    price: 2.00,
    category: Category.Shots,
    sales: 1200,
  },
  {
    id: "sho-ser",
    name: { en: "Service Shot", pt: "Shot" },
    description: { en: "Service drinks.", pt: "bebidas de serviço" },
    price: 2.50,
    category: Category.Shots,
    sales: 840,
  },
  {
    id: "sho-pre",
    name: { en: "Premium Shot", pt: "Shot Premium" },
    description: { en: "Premium drinks.", pt: "bebidas premium" },
    price: 5.00,
    category: Category.Shots,
    sales: 320,
  },
];


